Repository explosion/projects, pull requests merged in 2023-01, with the labels that each got.

#150 Add creation of projects.jsonl in docs update script
  .github/update_docs.py
  .github/update_projects_json.py
  README.md
  experimental/coref/README.md
  experimental/coref/project.yml
  experimental/ner_spancat_compare/README.md
  experimental/ner_spancat_compare/project.yml
  pipelines/floret_wiki_oscar_vectors/README.md
  pipelines/floret_wiki_oscar_vectors/project.yml
  projects.jsonl
  tutorials/ner_tweets/README.md
  tutorials/ner_tweets/project.yml
Labels: documentation, enhancement

#164 Revert "Update Python version for CI to 3.9"
  azure-pipelines.yml
  run-tests.sh
Labels: bug

#167 Move README contents from project.yml to README
  experimental/coref/README.md
  experimental/coref/project.yml
  experimental/ner_spancat_compare/README.md
  experimental/ner_spancat_compare/project.yml
  pipelines/floret_wiki_oscar_vectors/README.md
  pipelines/floret_wiki_oscar_vectors/project.yml
  tutorials/ner_tweets/README.md
  tutorials/ner_tweets/project.yml
Labels: documentation

#170 Demo project for edit-tree lemmatizer
  pipelines/README.md
  pipelines/edit_tree_lemmatizer/.gitignore
  pipelines/edit_tree_lemmatizer/README.md
  pipelines/edit_tree_lemmatizer/__init__.py
  pipelines/edit_tree_lemmatizer/project.yml
  pipelines/edit_tree_lemmatizer/test_project_etl.py
Labels: enhancement

#173 Update README for floret_wiki_oscar_vectors
  pipelines/floret_wiki_oscar_vectors/README.md
Labels: documentation

#171 Update READMEs
  experimental/README.md
  pipelines/edit_tree_lemmatizer/README.md
  tutorials/ner_multiple_trials/README.md
  tutorials/parser_low_resource/project.yml
  tutorials/textcat_goemotions/README.md
Labels: documentation

#166 Add script to generate projects.jsonl
  .github/update_projects_jsonl.py
  README.md
  projects.jsonl
Labels: documentation, enhancement

#160 Add automatic doc building
  .github/workflows/build-docs.yml
Labels: documentation, enhancement

#121 Remove dependency installation from project configs
  azure-pipelines.yml
  benchmarks/ner_conll03/project.yml
  benchmarks/parsing_penn_treebank/project.yml
  benchmarks/speed/project.yml
  benchmarks/speed/test_project_speed_benchmark.py
  benchmarks/textcat_architectures/project.yml
  benchmarks/textcat_architectures/requirements.txt
  benchmarks/textcat_architectures/test_project_textcat_arch.py
  benchmarks/ud_benchmark/requirements.txt
  experimental/ner_spancat_compare/project.yml
  integrations/fastapi/README.md
  integrations/fastapi/project.yml
  integrations/fastapi/test_project_fastapi.py
  integrations/huggingface_hub/README.md
  integrations/huggingface_hub/project.yml
  integrations/ray/project.yml
  integrations/streamlit/project.yml
  integrations/wandb/README.md
  integrations/wandb/project.yml
  integrations/wandb/requirements.txt
  pipelines/tagger_parser_ud/project.yml
  requirements.txt
  run-tests.sh
  tutorials/nel_emerson/project.yml
  tutorials/ner_drugs/project.yml
  tutorials/ner_tweets/project.yml
  tutorials/ner_tweets/requirements.txt
Labels: enhancement
